---

- name: Install Docker Compose plugin
  ansible.builtin.package:
    name: docker-compose-plugin
    state: present

- name: "Create working directory for Docker Compose service : {{ docker_compose_name | mandatory }}"
  ansible.builtin.file:
    path: "/opt/{{ docker_compose_name | mandatory }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: "Template [docker-compose.yml] into working directory for Docker Compose service : {{ docker_compose_name | mandatory }}"
  ansible.builtin.copy:
    content: |
      {{ docker_compose_content | mandatory }}
    dest: "/opt/{{ docker_compose_name | mandatory }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
  register: docker_compose_service_content

- name: "Template [.env] into working directory for Docker Compose service : {{ docker_compose_name | mandatory }}"
  when:
    - docker_compose_env is defined
    - docker_compose_env | length > 0
  ansible.builtin.copy:
    content: |
      {{ docker_compose_env }}
    dest: "/opt/{{ docker_compose_name | mandatory }}/.env"
    owner: root
    group: root
    mode: "0644"
  register: docker_compose_service_env

- name: "Create Docker Compose service : {{ docker_compose_name | mandatory }}"
  ansible.builtin.template:
    src: docker-compose.service.j2
    dest: "/etc/systemd/system/docker-compose_{{ docker_compose_name | mandatory }}.service"
    owner: root
    group: root
    mode: "0644"
  register: docker_compose_service

- name: "(Re)start Docker Compose service : {{ docker_compose_name | mandatory }}"
  when: docker_compose_service.changed or docker_compose_service_content.changed or docker_compose_service_env.changed
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    daemon_reload: true
    name: "docker-compose_{{ docker_compose_name | mandatory }}.service"
